In [1]:
import pandas as pd
dataset=pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [3]:
dataset["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [51]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={'weights':['uniform', 'distance'],'metric':['minkowski'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'n_neighbors':[6]}
grid=GridSearchCV(KNeighborsClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid=grid.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [52]:
grid_pred=grid.predict(X_test)
re=grid.cv_results_
rscore=grid.best_params_
print(f"The R_score value for best parameter:{rscore}")

The R_score value for best parameter:{'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 6, 'weights': 'distance'}

In [53]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005249,0.000287,0.010815,0.000669,auto,minkowski,6,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.763007,0.719604,0.661829,0.721268,0.700584,0.713258,0.032818,5
1,0.004954,0.000182,0.010964,0.000651,auto,minkowski,6,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.725502,0.703535,0.681761,0.758432,0.698113,0.713469,0.026481,1
2,0.005435,0.000500,0.013087,0.000486,ball_tree,minkowski,6,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.763007,0.719604,0.661829,0.721268,0.700584,0.713258,0.032818,5
3,0.005578,0.000933,0.011888,0.000478,ball_tree,minkowski,6,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.725502,0.703535,0.681761,0.758432,0.698113,0.713469,0.026481,1
4,0.008058,0.001965,0.012651,0.001304,kd_tree,minkowski,6,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.763007,0.719604,0.661829,0.721268,0.700584,0.713258,0.032818,5
5,0.006266,0.001096,0.011835,0.000513,kd_tree,minkowski,6,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.725502,0.703535,0.681761,0.758432,0.698113,0.713469,0.026481,1
6,0.005258,0.000386,0.011236,0.000671,brute,minkowski,6,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.763007,0.719604,0.661829,0.721268,0.700584,0.713258,0.032818,5
7,0.004854,0.000148,0.009351,0.000447,brute,minkowski,6,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.725502,0.703535,0.681761,0.758432,0.698113,0.713469,0.026481,1

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pred)
print(cm)

[[48  3]
 [28 54]]

In [55]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pred)
print(clf_report)

              precision    recall  f1-score   support

       False       0.63      0.94      0.76        51
        True       0.95      0.66      0.78        82

    accuracy                           0.77       133
   macro avg       0.79      0.80      0.77       133
weighted avg       0.83      0.77      0.77       133

In [56]:
from sklearn.metrics import roc_auc_score   ##roc_auc - receiver.operating.curve_area.under.curve
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])  ## grid.predict_proba - probability outputs from your tuned model (inside GridSearchCV)
                                                        ## [:,1] Take ALL rows, but only column index 1

0.816594930655189

In [57]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_pred,average='weighted')
print(f"f1_macro value for best parameter {rscore}:{f1_macro}")

f1_macro value for best parameter {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 6, 'weights': 'distance'}:0.7688978294600718